name:                stringlines
version:             0.1.0.0
github:              "lemald/stringlines"
license:             BSD3
author:              "Eddie Maldonado"
maintainer:          "eddie@lemald.org"
copyright:           "2018-2019 Eddie Maldonado"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/lemald/bus-scrape#readme>

dependencies:
- base >= 4.7 && < 5
- servant
- servant-client
- text
- time
- aeson
- yaml
- http-client
- http-client-tls
- http-media
- gpolyline
- jord
- sqlite-simple

library:
  source-dirs: src

executables:
  stringlines-poll:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stringlines
    - hslogger
  stringlines-chart:
    main:                Main.hs
    source-dirs:         chart
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stringlines
    - gnuplot
    - containers

tests:
  stringlines-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stringlines
    - tasty
    - tasty-hunit
